[package]
name = "rustgrep"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["cargo", "derive", "unstable-doc"] }
regex = "1.11.1"
thiserror = "2.0.7"

[features]
test_command = []
